- name: Query BIG-IP facts
  f5networks.f5_modules.bigip_device_info:
    provider: "{{ provider }}"
    gather_subset:
      - virtual-servers
      - ltm-pools
      - nodes
  connection: local
  delegate_to: localhost
  register: bigip_device_facts

- name: DISPLAY COMPLETE BIG-IP SYSTEM INFORMATION
  debug:
    var: bigip_device_facts

- name: Get failover state
  f5networks.f5_modules.bigip_command:
    provider: "{{ provider }}"
    commands:
      - show sys failover
  connection: local
  delegate_to: localhost
  register: failover_state

- name: Checking Failover states
  ansible.builtin.debug:
    var: failover_state
