- name: Create TCP monitor
  f5networks.f5_modules.bigip_monitor_tcp:
    name: "{{ monitor_name_var }}"
    send: "{{ monSend_var }}"
    receive: "{{ monRec_var }}"
    provider: "{{ provider }}"
  when: monitor_type == "TCP" and cus_monitor | bool

- name: Create UDP monitor
  f5networks.f5_modules.bigip_monitor_udp:
    name: "{{ monitor_name_var }}"
    send: "{{ monSend_var }}"
    receive: "{{ monRec_var }}"
    provider: "{{ provider }}"
  when: monitor_type == "UDP" and cus_monitor | bool

- name: Create HTTP monitor
  f5networks.f5_modules.bigip_monitor_http:
    name: "{{ monitor_name_var }}"
    send: "{{ monSend_var }}"
    receive: "{{ monRec_var }}"
    provider: "{{ provider }}"
  when: monitor_type == "HTTP" and cus_monitor | bool

- name: Create HTTPS monitor
  f5networks.f5_modules.bigip_monitor_https:
    name: "{{ monitor_name_var }}"
    send: "{{ monSend_var }}"
    receive: "{{ monRec_var }}"
    provider: "{{ provider }}"
  when: monitor_type == "HTTPS" and cus_monitor | bool

- name: Create ICMP monitor (fallback to HTTPS for typo?)
  f5networks.f5_modules.bigip_monitor_https:
    name: "{{ monitor_name_var }}"
    send: "{{ monSend_var }}"
    receive: "{{ monRec_var }}"
    provider: "{{ provider }}"
  when: monitor_type == "ICMP" and cus_monitor | bool
